default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: <%= ENV["DB_USER"] %>
  password: <%= ENV["APP_DATABASE_PASSWORD"] %>
  port: <%= ENV["APP_PORT"] %>

development:
  <<: *default
  database: testapp_development
  user: <%= ENV["DB_USER"] %>
  user: <%= ENV["APP_DATABASE_USER"] %>

test:
  <<: *default
  database: testapp_test

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: testapp_production
  username: <%= ENV["USER"] %> 
  password: <%= ENV["APP_DATABASE_PASSWORD"] %>
